### PR TITLE
Periodic merge of master (FreeREG) into FreeCEN

### PR DESCRIPTION
**Pull request by benwbrum**
We need to merge this manually to resolve conflicts.  This is likely a few hours of work, and needs to be tracked and planned.

### CODE REVIEW

**Comment by Captainkirkdawson** [comment]
I believe Vino is doing this systematically

**Comment by Captainkirkdawson** [comment]
I have no idea why wafflebot assigned this to me.

**Comment by richpomfret** [comment]
We should be reusing code where applicable - a merge is needed, first with an audit and then the process for merging is needed.

**Comment by Captainkirkdawson** [comment]
All code changes in master and freecen parsing should be in multi modal branch

**Pull request closed without merging**
