### PR TITLE
Fixed the options that were unavaible in files not processed

### PR DESCRIPTION
**Pull request by Vino-S**

### CODE REVIEW

**Comment by Sherlock21** [comment]
But how did the original action item get changed in the first place?

**Comment by Vino-S** [comment]
According to git history, a month ago Israel had added **has_access** condition to the SHOW, EDIT, REMOVE  buttons so that only system_admin and data_manager can get access to these buttons.
For list of files not processed the value of **has_access**  was not provided in the controller that was the reason we were unable to see these buttons.

**Comment by Sherlock21** [comment]
I am not sure which server you are are on here: I do our testing on T3 and production on Production of course. I can't access T2 because it does not work on my Safari Mac.

AND: i have had ACTIONS access to all the feature on both of the listings - 
Files Not Processed
and also the other one: Awaiting to be Processed.

SO it does seem that you are saying DM profile did not have actions on these listing before a month ago> - is that the correct understanding of what you say?

**Comment by SteveBiggs** [comment]
@Vino-S have you fixed the issue? I cannot see the SHOW, EDIT, REMOVE buttons in physical files in any of Production, test3 or test2. Thanks

**Comment by Vino-S** [comment]
Hi @SteveBiggs ,
I had pulled the changes in test2 and test3. Please have a look.

@Sherlock21 ,
You would have had access to those options before a month because there was no **has_access** condition.It had been added recently by Israel and there was a small bug which is the reason no one could have had access to SHOW, EDIT, Remove options.

**Comment by SteveBiggs** [comment]
Thanks Vino, the buttons are back on test2 and test3.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Vino-S** [comment]
Cheers. I will merge the changes to master

**Comment by Sherlock21** [comment]
In T3, all the right action buttons are there again. But there are no files awaiting in Awaiting to be Processed so I cant test that.

IN T3 there are plenty of files in: NotT Processed - so I sent one off for processing - that seems Ok. and I Removed one so that bit seems fine too.

Thank you

**Comment by Sherlock21** [comment]
Thank you.

**Pull request merged**
