### PR TITLE
Issue 1089

### PR DESCRIPTION
**Pull request by Captainkirkdawson**
Please review and pull into master. Has been tested by @edickens

### CODE REVIEW

**Comment by SteveBiggs** [comment]
@smrr723  when is this likely to be available on the production site? Thanks

**Comment by smrr723** [comment]
Hi @SteveBiggs - production gets updated with master once per sprint.  Next one is due Wed/Thursday next week after our meeting.  Does this need to be put into production before then?

**Comment by edickens** [comment]
Not showing in production yet.  I'll keep looking.  When it is I'll be sending a message to County Coordinators to get them started in sorting out the Unallocated Image Groups

**Comment by smrr723** [comment]
Won't be in production until Wednesday after our meeting @edickens.

The process we follow ATM is to merge individual completed Issues/Stories into the master branch here during the 2-week sprints, and then at the end of each sprint, run the update scripts to get that updated version of master into production.  The updated master branch isn't mirrored on to production automatically when you see it updated here - we have to manually update it.

Only for urgent issues like major bugs will we run an update earlier than the 2-week cycle.  Hope that clarifies!

**Pull request merged**
