### PR TITLE
Made SEO landing pages bi-modal with appropriate wording for FreeCEN

### PR DESCRIPTION
**Pull request by benwbrum**
This fixes the FreeREG-specific wording in templates and in the landing page data summaries.

### CODE REVIEW

**Comment by benwbrum** [comment]
cf #1902 

Once this is merged and the code is deployed, I will be able to set up the cron jobs according to Lemon's recommendations.

**Comment by Captainkirkdawson** [comment]
@benwbrum the code at https://github.com/FreeUKGen/MyopicVicar/commit/ceb47a30322f5b0ff3e3a3854d2341b25b90cda3#diff-9c3260c7f39a01831238c20697a55bb4R5-R12
is problematic. multimodal already runs freebmd hence the assigning all non freecen to freereg is not a good idea

**Comment by Captainkirkdawson** [comment]
same is likely true of 
https://github.com/FreeUKGen/MyopicVicar/commit/ceb47a30322f5b0ff3e3a3854d2341b25b90cda3#diff-45ba0f434147b8aeaed8794477cc123cL520-R525

**Comment by benwbrum** [comment]
Thanks, @Captainkirkdawson -- I'll get it switched.

**Comment by benwbrum** [comment]
@Captainkirkdawson Can you take a look at my most recent change with an eye to FreeBMD?  I don't have any way to test FreeBMD, but think the wording (at least) may not be flagrantly wrong now.

**Pull request merged**
