### PR TITLE
Refactored search record to handle new date storage

### PR DESCRIPTION
**Pull request by benwbrum**
Please review when convenient, @Captainkirkdawson or @dougkdev

### CODE REVIEW

**Comment by benwbrum** [comment]
I've defined new indexes, but have not tested them nor written the actuator code.

Previously, `search_date` was the trailing term on most indexes, following the "kitchen sink" approach to compound indexes.  Since the new date field requires doubling any index which uses `search_date`, and since index number and size has been a recurring bottleneck, I only doubled the date indexes in which date was important (i.e. there were fewer leading terms) and I got rid of the `search_date` term on remaining indexes.

Please take a look, @Captainkirkdawson

**Comment by Captainkirkdawson** [comment]
Made a couple of adjustments.
The vast majority of searches include a date field hence I think it important to have that the date fields in all indexes
Merged the pre and post indexes as we need to build the post indexes while continuing to support searches using the pre indexes
Since indexes are "smaller" under wired_tiger I think that will be OK

**Comment by Captainkirkdawson** [comment]
Have commenced the rebuild of the search records on test3

**Comment by Captainkirkdawson** [comment]
Now use a rails config field to control use of new search date field
Have tested indexes and hints. 
Only keep additional records from secondary search.
Code ready to be pulled into master

**Comment by Captainkirkdawson** [comment]
Will deploy after #942 wired tiger

**Comment by Captainkirkdawson** [comment]
Encountering checksum errors on the freereg1_csv_entries collection that are crashing mongodb
2016-09-29T15:48:14.725+0100 E STORAGE  [conn12] WiredTiger (0) [1475160494:725688][68969:0x818d5d800], file:index-307--8531000747577815162.wt, WT_CURSOR.remove: read checksum error for 8192B block at offset 679239680: calculated block checksum of 786064376 doesn't match expected checksum of 1048649802
2016-09-29T15:48:14.725+0100 E STORAGE  [conn12] WiredTiger (0) [1475160494:725729][68969:0x818d5d800], file:index-307--8531000747577815162.wt, WT_CURSOR.remove: index-307--8531000747577815162.wt: encountered an illegal file format or internal value
2016-09-29T15:48:14.725+0100 E STORAGE  [conn12] WiredTiger (-31804) [1475160494:725756][68969:0x818d5d800], file:index-307--8531000747577815162.wt, WT_CURSOR.remove: the process must exit and restart: WT_PANIC: WiredTiger library panic

**Comment by Captainkirkdawson** [comment]
Rebuilt indexes

**Pull request merged**
