### PR TITLE
Issue 522

### PR DESCRIPTION
**Pull request by smrr723**
Replace .empty? check with .blank? to account for nil cases

### CODE REVIEW

**Comment by Captainkirkdawson** [comment]
Yes

**Comment by smrr723** [comment]
@Captainkirkdawson rabbit hole full of your favourite .empty? errors here - now resolved.  Looks like similar issues exist on FR if you try and edit the country coordinators.

**Comment by Captainkirkdawson** [comment]
@smrr723 Do not believe we have an active issue as we have all county and country assigned. They are edited on a regular basis.

**Comment by smrr723** [comment]
@Captainkirkdawson Hmm, strange in that case - I still get an error when clicking on any of the edit buttons here - https://www.freereg.org.uk/countries? (logged in).

**Comment by edickens** [comment]
Me too.  But what can be Edited in Country?

**Comment by SteveBiggs** [comment]
Presumably should be able to edit any of these details? -
image

**Comment by Captainkirkdawson** [comment]
@smrr723 Guess I need to eat humble pie. Need to check facts before commenting in the future. Only saving grace for my red face is that county editing does work. You are correct country editing does not work on FR for the reason you have identified and which has been one of our bugbears. ie  that empty? crashes on a nil field which is why there has been the need to use  blank?

**Pull request merged**
