### PR TITLE
use downcase instead of upcase

### PR DESCRIPTION
**Pull request by israelriibeiro**
@Captainkirkdawson ,   as you said in #1040, this about.html.erb need a change.

screen shot 2017-02-11 at 5 39 22 pm

### CODE REVIEW

**Comment by Sherlock21** [comment]
Is this a full list of the abbreviations of Elizabeth? did i forget to add in the related Elyzabeth; Elyz:

can you get them added if not too much trouble please?

**Comment by israelriibeiro** [comment]
Hi, @Sherlock21 . 

I think we have to add this in the database.
```
irb(main):007:0> EmendationRule.where(replacement: 'elizabeth').to_a.count
=> 36 
irb(main):008:0> EmendationRule.where(replacement: 'elyzabeth').to_a.count
=> 0

```
 We have to change over here:
[Emendation](https://github.com/FreeUKGen/MyopicVicar/blob/master/lib/tasks/load_emendations.rake)

But, in this case, even if we've added elyzabeth to emendation rules, we wouldn't be able to show that information on this view, cause we use first_name as search criteria.

We can't show all that information unless all "El(i|y)(z|s)abeths" has the replacement in emendation_rule model, or we must search by similarity in database.

**Comment by Captainkirkdawson** [comment]
Sorry but simply adding a new rule does not propagate into the database. It
requires that the database be updated of all occurrences of records with
the new rule. There is no process to undertake this yet. Hence simply
adding the rule will be fake news!!

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by israelriibeiro** [comment]
Even if you add and run load_emendations rake task?!
I did not know that. Sorry for the fake news, @Sherlock21 and @Captainkirkdawson . auauha

**Comment by Captainkirkdawson** [comment]
You were not to know.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by AlOneill** [comment]
@Sherlock21 List shown above is _not_ complete. See full list for Elizabeth: 
http://www.freereg.org.uk/emendation_rules#e"

**Comment by edickens** [comment]
This is the first time I have really had a look at this list and a few 
things struck me immediately:-

- These are all First names.  This is not important.  Most people 
searching will use the last name and year range and omit the first 
name.  They will only use first name if they know exactly who they are 
looking for, or to reduce the number of results.  And if that does not 
work, then they will enter a Wildcard, such as El* if they were looking 
for Elizabeth. So is emendation of First Name really needed?  Yes, 
emendation of last name is needed because of spelling errors by the 
clerk when the person was illiterate.  I always cite the example of 
Dickens and Diggins that I have found.  But here Soundex comes into its own.

- Is a lot of processing speed needed for this, or is emendation only 
done on file upload to convert a name into a searchable version?

- This list is mainly abbreviations, such as just having a full stop on 
the end of the name.  I assume this is because these abbreviations have 
been found in the database.  But how often are they used?  Could the 
punctuation not be removed before matching to the emendation table?

- Some notable abbreviations are missing.  Elizabeth is often Liz, and 
Margaret is Peggy.  And there are many others.

- So sorry to be a killjoy at this late stage, but really why are we 
spending so much time on this?

Sincerely,

Eric

**Comment by Sherlock21** [comment]
Indeed, its first names only. this is what it was meant to be - surnames are handled as an entity on their own too.

This ( first names ) was the topic i was asked to run my eye over by BenB and add as necessary.

And as i see from this access: there is no entry of the spelling of Elyzabeth and derivatives. - that was the point of my first note. [having just done some Transcriptions for the 1670's and they use the basic spelling of: Elyzabeth and Elyz:

**Comment by Sherlock21** [comment]
Answering Eric D's point about Why are we bothering with First Names:

Well if its a common surname, and one omits a first name from a search, one hits the 250 records limit fairly easily if no year dates are specifies. If dates are added, even covering just a one year span, then one still hits the limit.

So to get any results at all, one has to start using first names. Simple as that.

**Comment by edickens** [comment]
Yes, but you can put a Wildcard in the search firstname which will 
reduce it a lot.  Emendation may only help in a very few cases.  E

**Comment by Captainkirkdawson** [comment]
This commentary by EricD is almost beyond belief. Emendations have been a
basic part of FR (2) since day one. They were always associated with First
Names.

From our help.
Forenames and abbreviations

Transcribers are encouraged to transcribe the forenames as they were
written in the register, except in those situations where the transcriber
is unable to input what was actually written. For instance, a horizontal
line was sometimes added to an abbreviation, (something like this: Wm.),
but this line cannot be entered easily into the database.

Because of the different ways of spelling a name, together with its
abbreviations, both in English and in Latin, the database will contain many
variations for a specific forename. *If the register states Gulielmus or
Gul. or Wm. or Willm. then this is what will be in the database if the
transcriber followed the rules. Many abbreviations and Latin names will be
found automatically, but we cannot guarantee that every possible variation
will be found.*

EricB spent  a long time reviewing what was in the database last year. We
updated the database based on his work late last year.

What is new is making the emendations visible!!

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Clearly the work of making them visible was extremely wothwhile

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I think my problem is that I don't know, even from the Help, what you do 
with this list.  Do you create an extra field with the "Standard" name 
at the time of uploading so that all the variations are catered for?  
And if you do, is this extra field the one that is searched or the TWYS 
version?  And can the researcher see the emendation so that they can 
understand why a record has been selected when they entered something 
else?  And if the researcher enters say "Eliz." will that be used to 
find all the variations that there are?

E


Eric J Dickens

**Comment by Captainkirkdawson** [comment]
Thank you @israelriibeiro

**Comment by Captainkirkdawson** [comment]
If you ask for a specific name then we also give you results for additional forenames; that is what I think it says. The purpose of this story was to show the researcher the variations that could have been included. in the Help and in the specific ones used in the search.

**Comment by Sherlock21** [comment]
Eric D

its easier if you try a small test search - this one shows well how it works: 

IN T3
Surname = BLAND
first name = John
County WRY
Place Sedbergh
type = burials
years = 1500 to 1800

the resulting list gives you all the clues
E

**Pull request merged**
