### PR TITLE
Issue 842 843

### PR DESCRIPTION
**Pull request by Vino-S**
Please review and let me know your feedback

### CODE REVIEW

**Comment by Captainkirkdawson** [comment]
I have pulled it into test3 for you to look at.

There is one issue that I can see. As an existing transcriber I decided to decline but looking at my profile shows true

**Comment by Vino-S** [comment]
Thanks Kirk.
I will have a look at the issue you mentioned.
I had also noticed that the styles that I had added for the agreement for both new and existing users is not shown. I will have a look at it and come back.

**Comment by Captainkirkdawson** [comment]
If I look at manage userids it shows me as declined.  There are 2 similar displays. my_own for my own profile and the show for managers looking at the profile. The latter has more information which is why I went with 2 displays.
The display of the field should in both cases be unknown until there is acceptance/decline or requested.

No one has accepted the new agreement

**Comment by Captainkirkdawson** [comment]
The styles is likely because I had not copied them into public

**Comment by Vino-S** [comment]
Can I create a method in model to update the value of Transcription agreement for all users from boolean values to "Unknown"?

**Comment by Sherlock21** [comment]
I logged on to T3 to have a look at the Agreement for Existing Transacribers.

May be too soon in your process?? Because I see only 2 options: Accept of Decline.
What happened to Pat's option of Not Now? 

Also, there is no clue as to what happens if I select Decline? I did not make any choice, because of the lack of information on this "What next" question.
Where does the transcriber go to to find these answers please? Or am I premature. - I need to use t3 for some other testing so we could do with sorting this one.

Does a decision here in T3 also apply to Production?
 
and if I make one or the other choice between the 2, just so I can get logged on to do my real testing, can I reverse that choice for my "real, Legal choice"

**Comment by Captainkirkdawson** [comment]
Test is test. Has anything you have done on test3 appeared in Production ?
No.

As to anthing else I cannot comment except to say the option are you
decline/accept. Prior to that you are unknown.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
I did not do anything in T3.

so there was nothing that could get into Production from yesterday’s attempted logon to T3.

but before that, there are many of my transcription files in T3.

So I am at this point, not worried.

I might at this point create a use my present ID to work as transcriptions only, and make a new ID for the DM activities - then it does not matter what I put as the Accept/Decline option.

E B

**Comment by Captainkirkdawson** [comment]
If I use the manage userid for a userid it still displays the bolean 
agreement1
If I try to edit there are only 2 options but we need to be able to use the other options of unknown and requested
agreement2
@PatReynolds please review on test3 for layout and content

**Comment by Vino-S** [comment]
Thanks Kirk.

Yes, the issue you mentioned is because of the boolean value existing in the database for other users. I updated  the value to unknown in my local using the following command 
(`UseridDetail.update_all(transcription_agreement: "Unknown")`)
and will it be a good idea to run a rake task to run once in all the database? 

Please advice

**Comment by Captainkirkdawson** [comment]
Yes we need a rake task to set all userid values to unknown

**Comment by Vino-S** [comment]
Hi,

I have corrected the code in `manage user id` to display from boolean values to the string values.

Added all the 4 options to the edit user page. So the user can view and select all four values.

Wrote a `Rake` task to update all the users `transcription_agreement` value from boolean(true or false) to `Unknown` by running `rake transcription_agreement_default_status_update`

Thanks

**Comment by Captainkirkdawson** [comment]
@PatReynolds commented elsewhere
As discussed in the last scrum, I am making mock-ups of two distinct sign-up pages (new transcribers and existing transcribers) development is on hold until I've done this (as, for example, it addresses Ali's point).
Seems we should hold off further development

**Comment by Vino-S** [comment]
Hi @Captainkirkdawson,
I started working on the Google Adsense Advertisement issues for Freecen. I will continue to work on this agreement once you have done the mock-ups, if any more changes needed.

**Comment by Captainkirkdawson** [comment]
@Vino-S  I am not working on any mock ups. That is @PatReynolds.
I am totally committed to sharding implementation.

**Pull request closed without merging**
