### PR TITLE
Meta descriptions

### PR DESCRIPTION
**Pull request by AJLeigh46**
@dougkdev  @waffle-iron Didn't realise meta descriptions for new sites had been set - was working off the currently live ones - so only a few tweaks.

### CODE REVIEW

**Comment by dougkdev** [comment]
This should be merged into freecen_parsing instead of master.

**Comment by Captainkirkdawson** [comment]
Do not understand the comment "the currently live ones" The new FreeREG is currently live

**Comment by Captainkirkdawson** [comment]
Have added the proposed change directly into Master since it is not yet app aware

**Comment by dougkdev** [comment]
Likewise added the Cen and BMD changes directly into freecen_parsing.

**Pull request closed without merging**
