### PR TITLE
Issue 1151

### PR DESCRIPTION
**Pull request by Vino-S**
Added open data status of transcribers to message system.

### CODE REVIEW

**Comment by Captainkirkdawson** [comment]
Vino 
Currently as implemented one has to select a single open data status. There needs to be an option to send the message to All of the options.
While you are at it can you add a link to the message edit action from the message show view
K

**Comment by Captainkirkdawson** [comment]
Vino 
A further more fundamental issue. The transcription agreement field in userid_details is currently a boolean true/false https://github.com/FreeUKGen/MyopicVicar/blob/master/app/models/userid_detail.rb#L37 so your selection method will not work as expected. The database also holds that field as boolean.

**Comment by Vino-S** [comment]
To update the transcription agreement status to **Unknown**(default value) for all users at database level I can write a rake task.

**Comment by Vino-S** [comment]
Do we need to fix transcription agreement status issue(for existing and new transcribers) before proceeding with this issue?

**Comment by Captainkirkdawson** [comment]
Likely the safest way is to create  a new field new_transcription_agreement and populate that with a rake task then any existiing code will continue to function then we have time to transfer all code using transcription_agreement

**Comment by Captainkirkdawson** [comment]
C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\controllers\userid_details_controller.rb:
  189      when params[:commit] == 'Register as Transcriber'
  190        @syndicates = Syndicate.get_syndicates_open_for_transcription
  191:       @transcription_agreement = [true,false]
  192        render :action => 'transcriber_registration' and return
  193      when params[:commit] == 'Technical Registration'
  ...
  391        @userid[:honeypot] = session[:honeypot]
  392        @syndicates = Syndicate.get_syndicates_open_for_transcription
  393:       @transcription_agreement = [true,false]
  394        @first_name = session[:first_name]
  395      else

C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\models\userid_detail.rb:
   35    field :digest, type: String, default: nil
   36    field :skill_notes, type: String
   37:   field :transcription_agreement, type: Boolean, default: false
   38    field :technical_agreement, type: Boolean, default: false
   39    field :research_agreement, type: Boolean, default: false
   ..
   56  
   57    validates_presence_of :userid,:syndicate,:email_address, :person_role, :person_surname, :person_forename,
   58:     :skill_level #,:transcription_agreement
   59    validates_format_of :email_address,:with => Devise::email_regexp
   60    validate :userid_and_email_address_does_not_exist, on: :create

C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\views\userid_details\_form.html.erb:
   38      <%= f.input :telephone_number,:label => "Telephone",:input_html => {:class => "simple_form_bgcolour", :size => 40 }%>
   39      <%= f.input :fiche_reader, :as => :boolean,boolean_style: :inline,:label => "Has a Fiche Reader?"%>
   40:     <%= f.input :transcription_agreement, :as => :boolean,:label => "Transcription agreement accepted?"%>
   41      <% unless session[:my_own] %>           
   42        <%= f.input :skill_level, :collection => UseridRole::SKILLS, :required => true, :include_blank => false,:label => "Transcription level skill",:input_html => {  :class => "text-input simple_form_bgcolour simple_form_position overide_selection_field_width",  :size => 4},:selected => "Learning" %>

C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\views\userid_details\my_own.html.erb:
   53      </tr>
   54      <tr>
   55:       <td>Transcription agreement accepted:</td><td > <%= @userid.transcription_agreement%>  </td>
   56      </tr>
   57      <tr>

C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\views\userid_details\researcher_registration.html.erb:
   44  Please read the researcher <%= link_to 'participation agreement', places_path%> and confirm that you accept these terms. PLEASE NOTE THE AGREEMENT IS NOT THERE YET
   45  </td><td>
   46: <%= f.input :transcription_agreement, {:as => :select,  :collection => [false,true], :include_blank => false, :required => true,:size => 35}%></td></tr>
   47  
   48  </table>

C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\views\userid_details\show.html.erb:
   69      </tr>
   70      <tr>
   71:       <td>Transcription agreement accepted:</td><td > <%= @userid.transcription_agreement%>  </td>
   72      </tr>
   73      <tr>

C:\Users\Kirk\Documents\GitHub\MyopicVicar\app\views\userid_details\technical_registration.html.erb:
   37  Please read the technical <%= link_to 'participation agreement', places_path%>  and confirm that you accept these terms.PLEASE NOTE THE AGREEMENT IS NOT THERE YET
   38  </td><td>
   39: <%= f.input :transcription_agreement, {:as => :select,  :collection => [false,true], :include_blank => false, :required => true,:size => 35}%></td></tr>
   40  
   41  </table>

C:\Users\Kirk\Documents\GitHub\MyopicVicar\lib\create_userid_docs.rb:
  212              header[:country_groups] = old_detail.country_groups
  213              header[:skill_notes] = old_detail.skill_notes
  214:             header[:transcription_agreement] = old_detail.transcription_agreement
  215              header[:technical_agreement] = old_detail.technical_agreement
  216              header[:research_agreement] = old_detail.research_agreement

11 matches across 8 files

**Pull request merged**
